<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static/assets/model/scene.gltf --transform
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/handpainted-watercolor-scene-0bd8711c1e944b159fdd0b47ca13c0d8
Title: Handpainted watercolor scene
-->

<script lang="ts">
	import { Group } from 'three';

	import { T } from '@threlte/core';
	import { useGltf, useGltfAnimations, useDraco } from '@threlte/extras';
	import { onMount } from 'svelte';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	ref = new Group();

	const dracoLoader = useDraco();
	const gltf = useGltf('./assets/model/scene-transformed.glb', {
		dracoLoader
	});

	export const { actions, mixer } = useGltfAnimations(gltf, ref);
	mixer.timeScale = 0.5;
	$effect(() => {
		if ($actions && $actions['Animation']) {
			$actions['Animation'].play();
		}
	});

	let rotations = $state(
		{
			alpha: 0,
			beta: 0,
			gamma: 0
		}
	);
	
	const rotationSpeed = 0.25;
	const rotationAmplitude = {
		alpha: 0.01,
		beta: 0.25,
		gamma: 0.01
	};
	
	onMount(() => {
		let frame: number;
		let startTime = performance.now();
		
		const animate = (time: number) => {
			const elapsed = (time - startTime) / 1000;
			rotations.alpha = Math.sin(elapsed * rotationSpeed) * rotationAmplitude.alpha;
			rotations.beta = Math.sin(elapsed * rotationSpeed) * rotationAmplitude.beta + 0.25;
			rotations.gamma = Math.sin(elapsed * rotationSpeed) * rotationAmplitude.gamma;
			frame = requestAnimationFrame(animate);
		};
		
		animate(startTime);
		
		return () => {
			cancelAnimationFrame(frame);
		};
	});
</script>

<T is={ref} dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.PerspectiveCamera
			makeDefault
			position={[15, 0, 15]}
			oncreate={(ref) => {
				ref.lookAt(0, 1, 0);
			}}
		></T.PerspectiveCamera>
		<T.Group name="Sketchfab_Scene" rotation={[rotations.alpha, rotations.beta, rotations.gamma]}>
			<T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
				<T.Group name="root">
					<T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
						<T.Group
							name="particle000_130"
							position={[0.17, -0.03, 5.1]}
							rotation={[-0.81, -0.63, -2.13]}
							scale={0.72}
						>
							<T.Mesh
								name="Object_239"
								geometry={gltf.nodes.Object_239.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle001_131"
							position={[1.2, 1.24, 6.81]}
							rotation={[-0.24, 0.5, -0.97]}
							scale={0.27}
						>
							<T.Mesh
								name="Object_241"
								geometry={gltf.nodes.Object_241.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle002_132"
							position={[1.7, 2.87, 4.21]}
							rotation={[-1.16, 1.39, -1.83]}
							scale={0.88}
						>
							<T.Mesh
								name="Object_243"
								geometry={gltf.nodes.Object_243.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle003_133"
							position={[-1.95, 1.31, 1.74]}
							rotation={[-2.16, 0.74, 1.51]}
							scale={0.42}
						>
							<T.Mesh
								name="Object_245"
								geometry={gltf.nodes.Object_245.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle004_134"
							position={[1.27, 2.69, 2.33]}
							rotation={[0.58, -0.76, -0.82]}
							scale={0.82}
						>
							<T.Mesh
								name="Object_247"
								geometry={gltf.nodes.Object_247.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle005_135"
							position={[1.37, 3.9, -0.68]}
							rotation={[-1.28, 0.54, -1.44]}
							scale={0.92}
						>
							<T.Mesh
								name="Object_249"
								geometry={gltf.nodes.Object_249.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle006_136"
							position={[3.17, 4.23, 2.13]}
							rotation={[0.61, 0.85, 2.5]}
							scale={0.46}
						>
							<T.Mesh
								name="Object_251"
								geometry={gltf.nodes.Object_251.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle007_137"
							position={[-2.15, 4.52, -0.91]}
							rotation={[0.68, 0.05, 1.63]}
							scale={0.48}
						>
							<T.Mesh
								name="Object_253"
								geometry={gltf.nodes.Object_253.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle008_138"
							position={[3.98, 5.04, 2.91]}
							rotation={[-0.5, -0.29, -0.99]}
							scale={0.5}
						>
							<T.Mesh
								name="Object_255"
								geometry={gltf.nodes.Object_255.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle009_139"
							position={[-3.48, 6.12, 1.3]}
							rotation={[-2.46, -1.2, -3.13]}
							scale={0.78}
						>
							<T.Mesh
								name="Object_257"
								geometry={gltf.nodes.Object_257.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle010_140"
							position={[-0.96, 6.89, 1.05]}
							rotation={[-2.24, -0.5, -2.05]}
							scale={0.92}
						>
							<T.Mesh
								name="Object_259"
								geometry={gltf.nodes.Object_259.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle011_141"
							position={[1.78, 7.59, 3.1]}
							rotation={[-0.43, -0.1, 0.01]}
							scale={0.3}
						>
							<T.Mesh
								name="Object_261"
								geometry={gltf.nodes.Object_261.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle012_142"
							position={[-2.3, 7, -2.97]}
							rotation={[1.36, 0.55, 0.08]}
							scale={0}
						>
							<T.Mesh
								name="Object_263"
								geometry={gltf.nodes.Object_263.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle013_143"
							position={[-1.76, 6.86, -3.97]}
							rotation={[1.49, -0.42, 2.37]}
							scale={0}
						>
							<T.Mesh
								name="Object_265"
								geometry={gltf.nodes.Object_265.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle014_144"
							position={[4.09, 6.82, -3.26]}
							rotation={[-3.11, -0.05, -2.73]}
							scale={0}
						>
							<T.Mesh
								name="Object_267"
								geometry={gltf.nodes.Object_267.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle015_145"
							position={[0.9, 6.84, -3.68]}
							rotation={[-1.74, 0.45, -1.51]}
							scale={0}
						>
							<T.Mesh
								name="Object_269"
								geometry={gltf.nodes.Object_269.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle016_146"
							position={[2.41, 7.8, 4.01]}
							rotation={[-0.31, -0.03, 1.05]}
							scale={0}
						>
							<T.Mesh
								name="Object_271"
								geometry={gltf.nodes.Object_271.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle017_147"
							position={[2.21, 7.02, -2.03]}
							rotation={[2.39, -0.15, 0.38]}
							scale={0}
						>
							<T.Mesh
								name="Object_273"
								geometry={gltf.nodes.Object_273.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle018_148"
							position={[1.67, 7.16, -1.03]}
							rotation={[-2.96, 0.41, -1.43]}
							scale={0}
						>
							<T.Mesh
								name="Object_275"
								geometry={gltf.nodes.Object_275.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle019_149"
							position={[0.99, 7.36, 0.35]}
							rotation={[0.97, 0.75, -1.38]}
							scale={0}
						>
							<T.Mesh
								name="Object_277"
								geometry={gltf.nodes.Object_277.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle020_150"
							position={[3.48, 7.71, 3.52]}
							rotation={[0.45, 1.05, 1.21]}
							scale={0}
						>
							<T.Mesh
								name="Object_279"
								geometry={gltf.nodes.Object_279.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle021_151"
							position={[1.53, 7.21, -0.65]}
							rotation={[2.47, -0.4, -0.93]}
							scale={0}
						>
							<T.Mesh
								name="Object_281"
								geometry={gltf.nodes.Object_281.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle022_152"
							position={[-0.89, 7.56, 1.58]}
							rotation={[2.11, -0.1, 0.65]}
							scale={0}
						>
							<T.Mesh
								name="Object_283"
								geometry={gltf.nodes.Object_283.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle023_153"
							position={[-0.6, 7.29, -0.43]}
							rotation={[-2.35, 0.87, -1.72]}
							scale={0}
						>
							<T.Mesh
								name="Object_285"
								geometry={gltf.nodes.Object_285.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle024_154"
							position={[-1.52, 7.18, -1.45]}
							rotation={[-2.48, 0.78, 2.43]}
							scale={0}
						>
							<T.Mesh
								name="Object_287"
								geometry={gltf.nodes.Object_287.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle025_155"
							position={[0.28, 7.82, 3.86]}
							rotation={[-0.98, 1.02, 2.33]}
							scale={0}
						>
							<T.Mesh
								name="Object_289"
								geometry={gltf.nodes.Object_289.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle026_156"
							position={[3.89, 7.61, 2.77]}
							rotation={[1.27, 0.38, -2.4]}
							scale={0}
						>
							<T.Mesh
								name="Object_291"
								geometry={gltf.nodes.Object_291.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle027_157"
							position={[1.95, 6.9, -3.04]}
							rotation={[-0.84, 0.3, 1.99]}
							scale={0}
						>
							<T.Mesh
								name="Object_293"
								geometry={gltf.nodes.Object_293.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle028_158"
							position={[-3.68, 7.63, 1.67]}
							rotation={[-2.96, -0.94, -1.21]}
							scale={0}
						>
							<T.Mesh
								name="Object_295"
								geometry={gltf.nodes.Object_295.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group
							name="particle029_159"
							position={[-1.67, 7.38, 0.06]}
							rotation={[2.44, -0.84, 2.68]}
							scale={0}
						>
							<T.Mesh
								name="Object_297"
								geometry={gltf.nodes.Object_297.geometry}
								material={gltf.materials['particles.002']}
							/>
						</T.Group>
						<T.Group name="Armature_44">
							<T.Group name="GLTF_created_0">
								<T is={gltf.nodes.GLTF_created_0_rootJoint} />
								<T.Group name="BezierCurve013_19">
									<T.Group name="BezierCurve014_0">
										<T.Mesh
											name="Object_9"
											geometry={gltf.nodes.Object_9.geometry}
											material={gltf.materials.branches}
										/>
										<T.Mesh
											name="Object_10"
											geometry={gltf.nodes.Object_10.geometry}
											material={gltf.materials.branch_linr}
										/>
									</T.Group>
								</T.Group>
								<T.SkinnedMesh
									name="Object_16"
									geometry={gltf.nodes.Object_16.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_16.skeleton}
									morphTargetDictionary={gltf.nodes.Object_16.morphTargetDictionary}
									morphTargetInfluences={gltf.nodes.Object_16.morphTargetInfluences}
								/>
								<T.SkinnedMesh
									name="Object_18"
									geometry={gltf.nodes.Object_18.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_18.skeleton}
									morphTargetDictionary={gltf.nodes.Object_18.morphTargetDictionary}
									morphTargetInfluences={gltf.nodes.Object_18.morphTargetInfluences}
								/>
								<T.SkinnedMesh
									name="Object_7"
									geometry={gltf.nodes.Object_7.geometry}
									material={gltf.materials.branches}
									skeleton={gltf.nodes.Object_7.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_12"
									geometry={gltf.nodes.Object_12.geometry}
									material={gltf.materials.branches}
									skeleton={gltf.nodes.Object_12.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_14"
									geometry={gltf.nodes.Object_14.geometry}
									material={gltf.materials.Material}
									skeleton={gltf.nodes.Object_14.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_20"
									geometry={gltf.nodes.Object_20.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_20.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_22"
									geometry={gltf.nodes.Object_22.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_22.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_24"
									geometry={gltf.nodes.Object_24.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_24.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_26"
									geometry={gltf.nodes.Object_26.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_26.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_28"
									geometry={gltf.nodes.Object_28.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_28.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_30"
									geometry={gltf.nodes.Object_30.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_30.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_32"
									geometry={gltf.nodes.Object_32.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_32.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_34"
									geometry={gltf.nodes.Object_34.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_34.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_36"
									geometry={gltf.nodes.Object_36.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_36.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_38"
									geometry={gltf.nodes.Object_38.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_38.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_40"
									geometry={gltf.nodes.Object_40.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_40.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_42"
									geometry={gltf.nodes.Object_42.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_42.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_44"
									geometry={gltf.nodes.Object_44.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_44.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_46"
									geometry={gltf.nodes.Object_46.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_46.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_48"
									geometry={gltf.nodes.Object_48.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_48.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_50"
									geometry={gltf.nodes.Object_50.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_50.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_52"
									geometry={gltf.nodes.Object_52.geometry}
									material={gltf.materials.Material}
									skeleton={gltf.nodes.Object_52.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_54"
									geometry={gltf.nodes.Object_54.geometry}
									material={gltf.materials.Material}
									skeleton={gltf.nodes.Object_54.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_56"
									geometry={gltf.nodes.Object_56.geometry}
									material={gltf.materials.Material}
									skeleton={gltf.nodes.Object_56.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_58"
									geometry={gltf.nodes.Object_58.geometry}
									material={gltf.materials.Material}
									skeleton={gltf.nodes.Object_58.skeleton}
								/>
							</T.Group>
						</T.Group>
						<T.Group name="Armature001_64" position={[4.52, -1.43, -1.41]}>
							<T.Group name="GLTF_created_1">
								<T is={gltf.nodes.GLTF_created_1_rootJoint} />
								<T.SkinnedMesh
									name="Object_99"
									geometry={gltf.nodes.Object_99.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_99.skeleton}
									morphTargetDictionary={gltf.nodes.Object_99.morphTargetDictionary}
									morphTargetInfluences={gltf.nodes.Object_99.morphTargetInfluences}
								/>
								<T.SkinnedMesh
									name="Object_101"
									geometry={gltf.nodes.Object_101.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_101.skeleton}
									morphTargetDictionary={gltf.nodes.Object_101.morphTargetDictionary}
									morphTargetInfluences={gltf.nodes.Object_101.morphTargetInfluences}
								/>
								<T.SkinnedMesh
									name="Object_81"
									geometry={gltf.nodes.Object_81.geometry}
									material={gltf.materials.branches}
									skeleton={gltf.nodes.Object_81.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_82"
									geometry={gltf.nodes.Object_82.geometry}
									material={gltf.materials.branch_linr}
									skeleton={gltf.nodes.Object_82.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_84"
									geometry={gltf.nodes.Object_84.geometry}
									material={gltf.materials.branches}
									skeleton={gltf.nodes.Object_84.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_85"
									geometry={gltf.nodes.Object_85.geometry}
									material={gltf.materials.branch_linr}
									skeleton={gltf.nodes.Object_85.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_87"
									geometry={gltf.nodes.Object_87.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_87.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_89"
									geometry={gltf.nodes.Object_89.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_89.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_91"
									geometry={gltf.nodes.Object_91.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_91.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_93"
									geometry={gltf.nodes.Object_93.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_93.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_95"
									geometry={gltf.nodes.Object_95.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_95.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_97"
									geometry={gltf.nodes.Object_97.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_97.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_103"
									geometry={gltf.nodes.Object_103.geometry}
									material={gltf.materials.Material}
									skeleton={gltf.nodes.Object_103.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_105"
									geometry={gltf.nodes.Object_105.geometry}
									material={gltf.materials.Material}
									skeleton={gltf.nodes.Object_105.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_107"
									geometry={gltf.nodes.Object_107.geometry}
									material={gltf.materials.Material}
									skeleton={gltf.nodes.Object_107.skeleton}
								/>
							</T.Group>
						</T.Group>
						<T.Group name="Armature002_111" position={[3.88, 2.59, -1.69]}>
							<T.Group name="GLTF_created_2">
								<T is={gltf.nodes.GLTF_created_2_rootJoint} />
								<T.SkinnedMesh
									name="Object_133"
									geometry={gltf.nodes.Object_133.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_133.skeleton}
									morphTargetDictionary={gltf.nodes.Object_133.morphTargetDictionary}
									morphTargetInfluences={gltf.nodes.Object_133.morphTargetInfluences}
								/>
								<T.SkinnedMesh
									name="Object_143"
									geometry={gltf.nodes.Object_143.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_143.skeleton}
									morphTargetDictionary={gltf.nodes.Object_143.morphTargetDictionary}
									morphTargetInfluences={gltf.nodes.Object_143.morphTargetInfluences}
								/>
								<T.SkinnedMesh
									name="Object_145"
									geometry={gltf.nodes.Object_145.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_145.skeleton}
									morphTargetDictionary={gltf.nodes.Object_145.morphTargetDictionary}
									morphTargetInfluences={gltf.nodes.Object_145.morphTargetInfluences}
								/>
								<T.SkinnedMesh
									name="Object_155"
									geometry={gltf.nodes.Object_155.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_155.skeleton}
									morphTargetDictionary={gltf.nodes.Object_155.morphTargetDictionary}
									morphTargetInfluences={gltf.nodes.Object_155.morphTargetInfluences}
								/>
								<T.SkinnedMesh
									name="Object_175"
									geometry={gltf.nodes.Object_175.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_175.skeleton}
									morphTargetDictionary={gltf.nodes.Object_175.morphTargetDictionary}
									morphTargetInfluences={gltf.nodes.Object_175.morphTargetInfluences}
								/>
								<T.SkinnedMesh
									name="Object_118"
									geometry={gltf.nodes.Object_118.geometry}
									material={gltf.materials.branches}
									skeleton={gltf.nodes.Object_118.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_119"
									geometry={gltf.nodes.Object_119.geometry}
									material={gltf.materials.branch_linr}
									skeleton={gltf.nodes.Object_119.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_121"
									geometry={gltf.nodes.Object_121.geometry}
									material={gltf.materials.branches}
									skeleton={gltf.nodes.Object_121.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_122"
									geometry={gltf.nodes.Object_122.geometry}
									material={gltf.materials.branch_linr}
									skeleton={gltf.nodes.Object_122.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_124"
									geometry={gltf.nodes.Object_124.geometry}
									material={gltf.materials.branches}
									skeleton={gltf.nodes.Object_124.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_125"
									geometry={gltf.nodes.Object_125.geometry}
									material={gltf.materials.branch_linr}
									skeleton={gltf.nodes.Object_125.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_127"
									geometry={gltf.nodes.Object_127.geometry}
									material={gltf.materials.branches}
									skeleton={gltf.nodes.Object_127.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_128"
									geometry={gltf.nodes.Object_128.geometry}
									material={gltf.materials.branch_linr}
									skeleton={gltf.nodes.Object_128.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_130"
									geometry={gltf.nodes.Object_130.geometry}
									material={gltf.materials.branches}
									skeleton={gltf.nodes.Object_130.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_131"
									geometry={gltf.nodes.Object_131.geometry}
									material={gltf.materials.branch_linr}
									skeleton={gltf.nodes.Object_131.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_135"
									geometry={gltf.nodes.Object_135.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_135.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_137"
									geometry={gltf.nodes.Object_137.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_137.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_139"
									geometry={gltf.nodes.Object_139.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_139.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_141"
									geometry={gltf.nodes.Object_141.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_141.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_147"
									geometry={gltf.nodes.Object_147.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_147.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_149"
									geometry={gltf.nodes.Object_149.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_149.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_151"
									geometry={gltf.nodes.Object_151.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_151.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_153"
									geometry={gltf.nodes.Object_153.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_153.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_157"
									geometry={gltf.nodes.Object_157.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_157.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_159"
									geometry={gltf.nodes.Object_159.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_159.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_161"
									geometry={gltf.nodes.Object_161.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_161.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_163"
									geometry={gltf.nodes.Object_163.geometry}
									material={gltf.materials['flowers.001']}
									skeleton={gltf.nodes.Object_163.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_165"
									geometry={gltf.nodes.Object_165.geometry}
									material={gltf.materials.Material}
									skeleton={gltf.nodes.Object_165.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_167"
									geometry={gltf.nodes.Object_167.geometry}
									material={gltf.materials.Material}
									skeleton={gltf.nodes.Object_167.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_169"
									geometry={gltf.nodes.Object_169.geometry}
									material={gltf.materials.Material}
									skeleton={gltf.nodes.Object_169.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_171"
									geometry={gltf.nodes.Object_171.geometry}
									material={gltf.materials.Material}
									skeleton={gltf.nodes.Object_171.skeleton}
								/>
								<T.SkinnedMesh
									name="Object_173"
									geometry={gltf.nodes.Object_173.geometry}
									material={gltf.materials.Material}
									skeleton={gltf.nodes.Object_173.skeleton}
								/>
							</T.Group>
						</T.Group>
						<T.Group name="BezierCurve010_113" position={[5.02, 0.38, -3.55]}>
							<T.Group name="BezierCurve009_112" position={[-0.39, 0.76, 1.27]}>
								<T.Mesh
									name="Object_199"
									geometry={gltf.nodes.Object_199.geometry}
									material={gltf.materials.branches}
								/>
								<T.Mesh
									name="Object_200"
									geometry={gltf.nodes.Object_200.geometry}
									material={gltf.materials.branch_linr}
								/>
							</T.Group>
							<T.Mesh
								name="Object_196"
								geometry={gltf.nodes.Object_196.geometry}
								material={gltf.materials.branches}
							/>
							<T.Mesh
								name="Object_197"
								geometry={gltf.nodes.Object_197.geometry}
								material={gltf.materials.branch_linr}
							/>
						</T.Group>
						<T.Group name="Cube_114" position={[1.88, 2.5, 0]}>
							<T.Mesh
								name="Object_202"
								geometry={gltf.nodes.Object_202.geometry}
								material={gltf.materials.lamp}
							/>
							<T.Mesh
								name="Object_203"
								geometry={gltf.nodes.Object_203.geometry}
								material={gltf.materials.Material}
							/>
						</T.Group>
						<T.Group name="Cube001_115">
							<T.Mesh
								name="Object_205"
								geometry={gltf.nodes.Object_205.geometry}
								material={gltf.materials.LAMP_DETAILS}
							/>
							<T.Mesh
								name="Object_206"
								geometry={gltf.nodes.Object_206.geometry}
								material={gltf.materials.Material}
							/>
						</T.Group>
						<T.Group
							name="BezierCurve_116"
							position={[0.92, 0.24, 0]}
							rotation={[Math.PI / 2, -Math.PI / 2, 0]}
						>
							<T.Mesh
								name="Object_208"
								geometry={gltf.nodes.Object_208.geometry}
								material={gltf.materials.LAMP_DETAILS}
							/>
							<T.Mesh
								name="Object_209"
								geometry={gltf.nodes.Object_209.geometry}
								material={gltf.materials.Material}
							/>
						</T.Group>
						<T.Group name="Cylinder_117" position={[0, -0.75, 0]}>
							<T.Mesh
								name="Object_211"
								geometry={gltf.nodes.Object_211.geometry}
								material={gltf.materials.LAMP_DETAILS}
							/>
							<T.Mesh
								name="Object_212"
								geometry={gltf.nodes.Object_212.geometry}
								material={gltf.materials.details_lineart}
							/>
						</T.Group>
						<T.Group name="Cylinder001_118" position={[1.88, 0.38, 0]}>
							<T.Mesh
								name="Object_214"
								geometry={gltf.nodes.Object_214.geometry}
								material={gltf.materials.LAMP_DETAILS}
							/>
							<T.Mesh
								name="Object_215"
								geometry={gltf.nodes.Object_215.geometry}
								material={gltf.materials.Material}
							/>
						</T.Group>
						<T.Group name="Cube004_119" position={[1.88, 2.5, 0]}>
							<T.Mesh
								name="Object_217"
								geometry={gltf.nodes.Object_217.geometry}
								material={gltf.materials.lamp}
							/>
							<T.Mesh
								name="Object_218"
								geometry={gltf.nodes.Object_218.geometry}
								material={gltf.materials.Material}
							/>
						</T.Group>
						<T.Group name="Cube006_125" position={[1.88, 2.5, 0]}>
							<T.Mesh
								name="Object_220"
								geometry={gltf.nodes.Object_220.geometry}
								material={gltf.materials.Material}
							/>
							<T.Mesh
								name="Object_221"
								geometry={gltf.nodes.Object_221.geometry}
								material={gltf.materials.Material}
							/>
							<T.Mesh
								name="Object_222"
								geometry={gltf.nodes.Object_222.geometry}
								material={gltf.materials.Material}
							/>
						</T.Group>
						<T.Group name="Cube007_126" position={[1.88, 2.5, 0]}>
							<T.Mesh
								name="Object_224"
								geometry={gltf.nodes.Object_224.geometry}
								material={gltf.materials.Material}
							/>
							<T.Mesh
								name="Object_225"
								geometry={gltf.nodes.Object_225.geometry}
								material={gltf.materials.Material}
							/>
							<T.Mesh
								name="Object_226"
								geometry={gltf.nodes.Object_226.geometry}
								material={gltf.materials.Material}
							/>
						</T.Group>
						<T.Group
							name="BezierCurve003_127"
							position={[0.92, 0.24, 0]}
							rotation={[Math.PI / 2, -Math.PI / 2, 0]}
						>
							<T.Mesh
								name="Object_228"
								geometry={gltf.nodes.Object_228.geometry}
								material={gltf.materials.Material}
							/>
							<T.Mesh
								name="Object_229"
								geometry={gltf.nodes.Object_229.geometry}
								material={gltf.materials.Material}
							/>
						</T.Group>
						<T.Group name="Cube008_128">
							<T.Mesh
								name="Object_231"
								geometry={gltf.nodes.Object_231.geometry}
								material={gltf.materials.Material}
							/>
							<T.Mesh
								name="Object_232"
								geometry={gltf.nodes.Object_232.geometry}
								material={gltf.materials.Material}
							/>
							<T.Mesh
								name="Object_233"
								geometry={gltf.nodes.Object_233.geometry}
								material={gltf.materials.Material}
							/>
							<T.Mesh
								name="Object_234"
								geometry={gltf.nodes.Object_234.geometry}
								material={gltf.materials.Material}
							/>
						</T.Group>
						<T.Group name="Cylinder003_129" position={[1.88, 0.38, 0]}>
							<T.Mesh
								name="Object_236"
								geometry={gltf.nodes.Object_236.geometry}
								material={gltf.materials.Material}
							/>
							<T.Mesh
								name="Object_237"
								geometry={gltf.nodes.Object_237.geometry}
								material={gltf.materials.Material}
							/>
						</T.Group>
					</T.Group>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
